### ISSUE TITLE
Doesn't work well with cloth simulation.

### ISSUE THREAD

**Issue by lujaguru** [OtherRealms/Proximity#1]
I tried to get the tension weights on cloth simulation, but the simulation seems to get weird after turning on proximity tension addon. The addon changes the initial shape of the cloth during simulation.

https://user-images.githubusercontent.com/85117493/123324124-318a8f00-d556-11eb-920a-ca4aa58f0fdf.mp4

**Comment by OtherRealms** [comment]
Hi I haven't tried it with cloth myself, I'll see if possible.

**Comment by OtherRealms** [comment]
![cloth](https://user-images.githubusercontent.com/58406975/123358472-e0f35000-d5ae-11eb-958d-3b9bc4eefd40.JPG)

I was able to get it to work using the following steps

- turn off live button (top left of the panel)
- bake animation
- add a corrective smooth modifier makes the results much nicer and enhances the tension, keep rest source as 'Original Coords', you'll proably also want pin boundaries and repeat a few time to make the mesh less jagged
- turn on live button

I'm not sure why or how the addon is interfering with simulations. I'll look into that. thnx

**Comment by OtherRealms** [comment]
The updated version will avoid calculating tension on un-cached cloth sims to avoid interfering, A warning is also displayed.
